os: linux
dist: focal
language: python
python: 3.9
cache: pip
addons:
  apt:
    packages:
      - libatlas-base-dev
      - liblapack-dev
      - gfortran
      - libgmp-dev 
      - libmpfr-dev
      - libsuitesparse-dev
      - ccache
      - libmpc-dev
env:
  - PATH=$PATH:$HOME/.cargo/bin
before_install:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - pip install --upgrade pip setuptools six wheel
  - pip install statsmodels
jobs:
  include:
    - install: true
      script: pip install tensorflow
    - name: Build
      install: pip install pytest-cov -r requirements.txt
      script:
        - pytest --doctest-modules --ignore=project_euler/ --cov-report=term-missing:skip-covered --cov=. .
  allow_failures:
    - install: true
after_success:
  - scripts/build_directory_md.py 2>&1 | tee DIRECTORY.md
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
